version: 2
jobs:
  build:
    docker:
      # https://circleci.com/docs/2.0/circleci-images/#openjdk
      - image: circleci/openjdk:11.0.1-jdk

    working_directory: ~/api-rest-k1-v1

    steps:
      # git pull
      - checkout
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: mvn dependency:go-offline

      # package into a jar
      - run: mvn clean package

      # build and push docker image to docker hub
      - run: mvn clean compile jib:build -Dimage=joset0899/api-rest:1.0.0

      # store raw contents of src code
      - store_artifacts:
          path: target/classes
          destination: api-rest-k1-v1